www/app/protected/controllers/ApiController.php
<?php

require_once Yii::getPathOfAlias('application.extensions.JsonRpc') . DIRECTORY_SEPARATOR . 'Server.php';
require_once Yii::getPathOfAlias('application.extensions.JsonRpc.Transport') . DIRECTORY_SEPARATOR . 'BasicServer.php';

class ApiController extends BaseController
{
    public $layout = false;

    public function accessRules()
    {
        return array(
            array('allow'),
        );
    }

    protected function beforeAction($action)
    {
        if (!parent::beforeAction($action)) {
            return false;
        }

        foreach (Yii::app()->log->routes as $route) {
            if ($route instanceof CWebLogRoute) {
                $route->enabled = false;
            }
        }

        return true;
    }

    public function actionIndex()
    {
        $server = new JsonRpc\Server(Yii::app()->api);

        if (Yii::app()->request->isPostRequest) {
            header('Content-Type: application/json');
            $server->receive();
            Yii::app()->end();
        }

        echo 'SMD here';
        Yii::app()->end();
    }

}

www/app/protected/controllers/PartiesController.php
<?php

class PartiesController extends BaseController
{
	public $pageTitle = 'Мои партии';

	public function init()
	{
		parent::init();

		$this->breadcrumbs = array(
			$this->pageTitle => array( 'index' ),
		);
	}

	public function accessRules()
	{
		return array_merge(
			array(),
			parent::accessRules()
		);
	}

	public function filters()
	{
		return array_merge(
			array(
				'postOnly + delete'
			),
			parent::filters()
		);
	}

	public function actionIndex()
	{
		$this->render( 'index', array(
			'parties' => Yii::app()->user->session->user->parties,
		) );
	}

	public function actionView( $uid = null )
	{
		$model = $this->loadParty( null, $uid );

		if ( !$model->isPartyMember() )
			$this->throwHttpException( 403, 'Чтобы просматривать страницу партии, нужно быть ее членом.' );

		$this->render( 'view', array(
			'model' => $model,
		) );
	}

	public function actionInvite( $uid )
	{
		$model = $this->loadParty( null, $uid );

		if ( !$model->isPartyMember() )
			$this->throwHttpException( 403, 'Чтобы просматривать страницу партии, нужно быть ее членом.' );

		$this->render( 'invite', array(
			'model' => $model,
		) );
	}

	public function actionJoin( $uid )
	{
		$model = $this->loadParty( null, $uid );

		if ( $model->isPartyMember() )
			$this->throwHttpException( 403, 'Вы уже вступили в эту партию.' );

		if ( Yii::app()->request->getIsPostRequest() )
		{
			if ( $model->joinUser() )
				$this->redirect( array( 'view', 'uid' => $model->uri_name ) );
		}

		$this->render( 'join', array(
			'model' => $model,
		) );
	}

	public function actionCreate()
	{
		$model = new Parties;

		$this->performAjaxValidation( $model );

		if ( isset( $_POST[ 'Parties' ] ) )
		{
			if ( $model->create( $_POST[ 'Parties' ] ) )
				$this->redirect( array( 'view', 'uid' => $model->uri_name ) );
		}

		$this->render( 'create', array(
			'model' => $model,
		) );
	}

	public function loadParty( $id = null, $uri_name = null )
	{
		/**/
		if ( isset( $id ) )
			return parent::loadModel( 'Parties', $id );
		else if ( isset( $uri_name ) )
			return parent::loadModel( 'Parties', $uri_name, 'uri_name' );

		$this->throwHttpException( 400, 'Отсутствует идентификатор партии.' );
	}

	protected function performAjaxValidation( $model )
	{
		if ( isset( $_POST[ 'ajax' ] ) && $_POST[ 'ajax' ] === 'parties-form' )
		{
			echo CActiveForm::validate( $model );
			Yii::app()->end();
		}
	}
}

www/app/protected/controllers/SiteController.php
<?php

class SiteController extends BaseController
{
	public $pageTitle = 'Welcome to Учёт Бабла';

	public function init()
	{
		parent::init();

		$this->breadcrumbs = array(
			$this->pageTitle => array( 'index' ),
		);
	}

	public function accessRules()
	{
		return array_merge(
			array(
				array( 'allow',
					/*'actions' => array('error')*/ ),
			),
			parent::accessRules()
		);
	}

	public function actions()
	{
		return array(
			'captcha' => array(
				'class' => 'CCaptchaAction',
				'backColor' => 0xFFFFFF,
			),
			'page' => array(
				'class' => 'CViewAction',
			),
		);
	}

	public function actionIndex()
	{
		$this->render( 'index' );
	}

	public function actionError()
	{
		if ( $error = Yii::app()->errorHandler->error )
		{
			if ( Yii::app()->request->isAjaxRequest )
				echo $error[ 'message' ]; // TODO
			else
				$this->render( 'error', $error );
		}
	}
	
	public function actionSendNotifications()
	{
		$users = Users::model()->findAllByAttributes( array(),
			'(`disabled` IS NULL OR `disabled` = 0 ) AND ( `locked_till` IS NULL OR `locked_till` < :current_timestamp ) AND `email` IS NOT NULL',
			array( ':current_timestamp' => time() ) );
		foreach ( $users as $user )
		{
			$transfers = new Transfers;
			$transfers->chiperkey = $user->salt;
			$creditors = $transfers->getCreditors();
			
			if ( empty( $creditors ) )
				continue;
			
			try
			{
				$email = Yii::app()->email;
				$email->to = $user->email;
				$email->view = 'notification';
				$email->viewVars = array(
					'user' => $user,
					'creditors' => $creditors,
				);
				$email->send();
			}
			catch (Exception $exception)
			{
				echo Yii::t( 'app', 'Something is going wrong when trying to send notification to {email}: {message}', array( '{email}' => $user->email, '{message}' => $exception->getMessage() ) );
			}
		}
	}

	public function actionContact()
	{
		$model = new ContactForm;
		if ( isset( $_POST[ 'ContactForm' ] ) )
		{
			$model->attributes = $_POST[ 'ContactForm' ];
			if ( $model->validate() )
			{
				$name = '=?UTF-8?B?'.base64_encode( $model->name ).'?=';
				$subject = '=?UTF-8?B?'.base64_encode( $model->subject ).'?=';
				$headers = "From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-type: text/plain; charset=UTF-8";

				mail( Yii::app()->params[ 'adminEmail' ], $subject, $model->body, $headers );
				Yii::app()->user->setFlash( 'contact', 'Thank you for contacting us. We will respond to you as soon as possible.' );
				$this->refresh();
			}
		}
		$this->render( 'contact', array( 'model' => $model ) );
	}
}

;

www/app/protected/controllers/TransfersController.php
<?php

class TransfersController extends BaseController
{
	public $pageTitle = 'Мои переводы';

	public function init()
	{
		parent::init();

		$this->breadcrumbs = array(
			$this->pageTitle => array( 'index' ),
		);
	}

	public function accessRules()
	{
		return array_merge(
			array(),
			parent::accessRules()
		);
	}

	public function filters()
	{
		return array_merge(
			array(
				'postOnly + delete'
			),
			parent::filters()
		);
	}

	public function actionIndex()
	{
		$pages = new CPagination( Transfers::model()->getHistoryCount() );
		$pages->pageSize = 10;

		$transfers = Transfers::model()->getHistory( $pages->limit, $pages->offset );

		$this->render( 'index', array(
			'transfers' => $transfers,
			'pages' => $pages,
		) );
	}

	public function actionTotal()
	{
		$this->render( 'total', array(
			'creditors' => Transfers::model()->getCreditors(),
			'debtors' => Transfers::model()->getDebtors(),
		) );
	}

	public function actionView( $id )
	{
		$model = Transfers::model()->getTransfer( $id );

		if ( $model === null )
			throwHttpNotFound( 'Запрошенный перевод не существует' );

		$this->render( 'view', array(
			'model' => $model,
		) );
	}

	public function actionCreate( $party_id = null, $source_user_id = null, $target_user_id = null )
	{
		$party_members = array( Yii::app()->user->session->user );
		$source_user = null;
		$target_user = null;

		if ( isset( $party_id ) )
		{
			$party = parent::loadModel( 'Parties', $party_id );
			$party_members = $party->users;
		}

		if ( isset( $source_user_id ) )
		{
			$source_user = parent::loadModel( 'Users', $source_user_id );
			$party_members[ ] = $source_user;
		}

		if ( isset( $target_user_id ) )
		{
			$target_user = parent::loadModel( 'Users', $target_user_id );
			$party_members[ ] = $target_user;
		}

		if ( empty( $party_members ) )
			$this->throwHttpException( 400, 'Неверный запрос. Не указаны обязательные параметры.' );

		$model = new Transfers;

		$this->performAjaxValidation( $model );

		if ( isset( $_POST[ 'Transfers' ] ) )
		{
			if ( $model->create( $_POST[ 'Transfers' ] ) )
			{
				Yii::app()->user->setFlash( 'system-highlight', 'Ваш перевод успешно создан.<br />'.XHtml::link( 'Создать еще один', array( 'create', 'party_id' => $party_id ) ) );
				$this->redirect( array( 'index' ) );
			}
		}

		$this->render( 'create', array(
			'model' => $model,
			'party_members' => $party_members,
			'source_user' => $source_user,
			'target_user' => $target_user,
		) );
	}

	public function actionCreateMultiple( $party_id )
	{
		$party = parent::loadModel( 'Parties', $party_id );

		$model = new Transfers;

		$this->performAjaxValidation( $model );

		if ( isset( $_POST[ 'Transfers' ] ) )
		{
			if ( $model->create( $_POST[ 'Transfers' ] ) )
			{
				Yii::app()->user->setFlash( 'system-highlight', 'Ваш перевод успешно создан.<br />'.XHtml::link( 'Создать еще один', array( 'create', 'party_id' => $party_id ) ) );
				$this->redirect( array( 'index' ) );
			}
		}

		$this->render( 'create_multiple', array(
			'model' => $model,
			'party_members' => $party->users,
		) );
	}

	protected function performAjaxValidation( $model )
	{
		if ( isset( $_POST[ 'ajax' ] ) && $_POST[ 'ajax' ] === 'transfers-form' )
		{
			echo CActiveForm::validate( $model );
			Yii::app()->end();
		}
	}
}

;

www/app/protected/controllers/UsersController.php
<?php

class UsersController extends BaseController
{
	public $pageTitle = 'Пользователи';

	public function init()
	{
		parent::init();

		$this->breadcrumbs = array(
			$this->pageTitle => array( 'index' ),
		);
	}

	public function accessRules()
	{
		return array_merge(
			array(
				array( 'allow',
					'actions' => array( 'index', 'login', 'vkauth' ) ),
			),
			parent::accessRules()
		);
	}

	public function actionIndex()
	{
		$this->redirect( '/users/login' );
	}

	public function actionLogin()
	{
		if ( !Yii::app()->user->isGuest )
			$this->redirect( Yii::app()->homeUrl );

		$model = new LoginForm;

		if ( isset( $_POST[ 'ajax' ] ) && $_POST[ 'ajax' ] === 'login-form' )
		{
			echo CActiveForm::validate( $model );
			Yii::app()->end();
		}

		if ( isset( $_POST[ 'LoginForm' ] ) )
		{
			$model->attributes = $_POST[ 'LoginForm' ];

			if ( $model->validate() && $model->login() )
				$this->redirect( Yii::app()->request->urlReferrer ? Yii::app()->request->urlReferrer : Yii::app()->returnUrl );
		}

		$this->render( 'login', array( 'model' => $model ) );
	}

	public function actionVkauth()
	{
		if ( !Yii::app()->user->isGuest )
			$this->redirect( Yii::app()->homeUrl );

		$user_identity = new VkAppIdentity();
		$user_identity->authenticate();

		if ( $user_identity->errorCode === BaseIdentity::ERROR_NONE &&
			Yii::app()->user->login( $user_identity )
		)
		{
			$this->redirect( Yii::app()->request->urlReferrer ? Yii::app()->request->urlReferrer : Yii::app()->returnUrl );
		}

		$this->redirect( '/users/login' );
	}

	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect( Yii::app()->request->urlReferrer ? Yii::app()->request->urlReferrer : Yii::app()->homeUrl );
	}

	public function actionEmail()
	{
		$model = new EmailForm;

		if ( isset( $_POST[ 'ajax' ] ) && $_POST[ 'ajax' ] === 'email-form' )
		{
			echo CActiveForm::validate( $model );
			Yii::app()->end();
		}

		if ( isset( $_POST[ 'EmailForm' ] ) )
		{
			$model->attributes = $_POST[ 'EmailForm' ];

			if ( $model->validate() && $model->setEmail() )
				$this->redirect( Yii::app()->homeUrl );
		}

		$this->render( 'email', array( 'model' => $model ) );
	}

	public function actionBankAccount()
	{
		$model = BankAccounts::model()->findByAttributes( array(
			'user_id' => Yii::app()->user->id
		) );

		if ( $model === null )
			$model = new BankAccounts;

		if ( isset( $_POST[ 'ajax' ] ) && $_POST[ 'ajax' ] === 'bank-account-form' )
		{
			echo CActiveForm::validate( $model );
			Yii::app()->end();
		}

		if ( isset( $_POST[ 'BankAccounts' ] ) )
		{
			$model->attributes = $_POST[ 'BankAccounts' ];
			$model->user_id = Yii::app()->user->id;

			if ( $model->save() )
				$this->redirect( Yii::app()->homeUrl );
		}

		$this->render( 'bankAccount', array( 'model' => $model ) );
	}

}

www/app/protected/views/controllers/transfers/create.php
<?php

Yii::app()->clientScript->registerCssFile( Yii::app()->assetManager->publish( 'styles/transfers/create.css' ) );

$this->pageTitle = 'Создать перевод';
$this->breadcrumbs = array_merge( $this->breadcrumbs,
	array( $this->pageTitle => array( 'create' ) ) );

$party_member_items = array( 'empty' => '' );

foreach ( $party_members as $member )
{
	$party_member_items[ $member->id ] = $member->getName();
	if ( $member->id === Yii::app()->user->id )
		$party_member_items[ $member->id ] .= ' (Я)';
}

$this->widget( 'XActiveForm', array(
	'id' => 'transfers-form',
	'enableAjaxValidation' => true,
	'clientOptions' => array(
		'validateOnSubmit' => true,
		'validateOnChange' => false,
	),
	'model' => $model,
	'fields' => array
	(
		'source_user_id' => array( 'type' => 'dropdown', 'items' => $party_member_items, 'selected' => ( isset( $source_user ) ? $source_user->id : Yii::app()->user->id ) ),
		'target_user_id' => array( 'type' => 'dropdown', 'items' => $party_member_items, 'selected' => ( isset( $target_user ) ? $target_user->id : ( isset( $source_user ) ? Yii::app()->user->id : 'empty' ) ) ),
		'value' => array( 'hint' => 'В качестве дробного разделителя используется точка' ),
		'comment' => array( 'type' => 'textarea' ),
	),
) );

?>

<?php if ( isset( $target_user ) && !empty( $target_user->bank_account ) ): ?>
	<?php
	$labels = BankAccounts::model()->attributeLabels();
	?>
	<p>Реквизиты получателя перевода:</p>
	<table class="bank-account">
		<tbody>
		<?php foreach ( $target_user->bank_account->safeAttributeNames as $attribute ): ?>
			<tr>
				<th><?php echo isset( $labels[ $attribute ] ) ? $labels[ $attribute ] : $attribute; ?></th>
				<td><?php echo $target_user->bank_account->{$attribute}; ?></td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
<?php endif; ?>

www/app/protected/views/controllers/transfers/create_multiple.php
<?php

$this->pageTitle = 'Создать перевод многим';
$this->breadcrumbs = array_merge( $this->breadcrumbs,
	array( $this->pageTitle => array( 'create' ) ) );

$party_member_items = array();

foreach ( $party_members as $member )
{
	$party_member_items[ $member->id ] = $member->getName();
	if ( $member->id === Yii::app()->user->id )
		$party_member_items[ $member->id ] .= ' (Я)';
}

$this->widget( 'XActiveForm', array(
	'id' => 'transfers-form',
	'enableAjaxValidation' => true,
	'clientOptions' => array(
		'validateOnSubmit' => true,
		'validateOnChange' => false,
	),
	'model' => $model,
	'fields' => array
	(
		'source_user_id' => array( 'type' => 'dropdown', 'items' => $party_member_items, 'selected' => Yii::app()->user->id ),
		'target_user_id' => array( 'type' => 'checkboxlist', 'items' => $party_member_items ),
		'value' => array( 'hint' => 'Введите ОБЩУЮ сумму перевода' ),
		'comment' => array( 'type' => 'textarea' ),
	),
) );

?>
<style type="text/css">
	.coef-input
	{
		width: 50px;
		height: 20px;
	}
</style>
<script type="application/javascript">
$(function()
{
	$.each( $( '#Transfers_target_user_id > input[type="checkbox"]' ),
	        function( i, val )
	        {
	        	var checkbox = $( val );
	        	var coef_input = $( '<input class="coef-input" type="number" value="1" />' );
	        	coef_input.attr( 'name', 'Transfers[target_coefs][' + checkbox.val() + ']' );
	        	coef_input.insertBefore( checkbox );
	        } );
} );
</script>

www/app/protected/views/controllers/transfers/index.php
<?php

Yii::app()->clientScript->registerCssFile( Yii::app()->assetManager->publish( 'styles/transfers/index.css' ) );

echo XHtml::link( 'Сводная таблица', array( '/transfers/total' ), array( 'class' => 'big-link float-right' ) );

$first_number_in_page = $pages->itemCount - $pages->limit * $pages->currentPage;
$last_number_in_page = $pages->itemCount - $pages->limit * ( $pages->currentPage + 1 ) + 1;
$last_number_in_page = $last_number_in_page >= 1 ? $last_number_in_page : 1;

?>

<div>

	<div class="mainbar">

		В списке представлены переводы с <?php echo $first_number_in_page; ?>
		по <?php echo $last_number_in_page; ?>:

		<table class="transfer-history">
			<thead>
			<tr>
				<th>Дата</th>
				<th>Источник</th>
				<th>Получатель</th>
				<th>Сумма</th>
				<th></th>
			</tr>
			</thead>
			<tbody>
			<?php foreach ( $transfers as $transfer ): ?>
				<tr>
					<td><?php echo date( 'd M Y', $transfer->timestamp ); // D, d M Y H:i ?></td>
					<td><?php echo $transfer->source_user->getName(); ?></td>
					<td><?php echo $transfer->target_user->getName(); ?></td>
					<td><?php echo $transfer->value; ?></td>
					<td><?php echo XHtml::link( 'Детали', array( 'view', 'id' => $transfer->id ) ); ?></td>
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>

		<?php $this->widget( 'CLinkPager', array(
			'htmlOptions' => array(
				'class' => 'link-pager',
			),
			'header' => 'Страницы: ',
			'firstPageLabel' => 'первая',
			'lastPageLabel' => 'последняя',
			'nextPageLabel' => 'вперед',
			'prevPageLabel' => 'назад',
			'cssFile' => Yii::app()->assetManager->publish( 'styles/pager.css' ),
			'pages' => $pages
		) ); ?>

	</div>

	<div class="sidebar navigation-links">
		<?php $this->renderPartial( '_navigation_links' ); ?>
	</div>

</div>

www/app/protected/views/controllers/transfers/total.php
<?php

Yii::app()->clientScript->registerCssFile( Yii::app()->assetManager->publish( 'styles/transfers/total.css' ) );

$this->pageTitle = 'Сводная таблица';
$this->breadcrumbs = array_merge( $this->breadcrumbs,
	array( $this->pageTitle => array( 'total' ) ) );

?>

<div>

	<table class="total-lists-united">
		<tbody>
		<tr>
			<td>

				Мне должны:
				<table class="total-list">
					<thead>
					<tr>
						<th>Источник</th>
						<th>Сумма</th>
					</tr>
					</thead>
					<tbody>
					<?php foreach ( $debtors as $item )
					{ ?>
						<tr>
							<td><?php echo XHtml::link( $item->user->getName(), array( 'create', 'source_user_id' => $item->user->id ) ); ?></td>
							<td><?php echo $item->value; ?></td>
						</tr>
					<?php } ?>
					</tbody>
				</table>

			</td>
			<td>

				Я должен:
				<table class="total-list">
					<thead>
					<tr>
						<th>Получатель</th>
						<th>Сумма</th>
					</tr>
					</thead>
					<tbody>
					<?php foreach ( $creditors as $item )
					{ ?>
						<tr>
							<td><?php echo XHtml::link( $item->user->getName(), array( 'create', 'target_user_id' => $item->user->id ) ); ?></td>
							<td><?php echo $item->value; ?></td>
						</tr>
					<?php } ?>
					</tbody>
				</table>

			</td>
		</tr>
		</tbody>
	</table>

	<p>Щелкните на имени в списке должников или кредиторов для быстрого открытия формы перевода.</p>

</div>

www/app/protected/views/controllers/transfers/view.php
<?php

Yii::app()->clientScript->registerCssFile( Yii::app()->assetManager->publish( 'styles/transfers/view.css' ) );

$this->pageTitle = 'Перевод #'.$model->id;
$this->breadcrumbs = array_merge( $this->breadcrumbs,
	array( $this->pageTitle => array( 'view', 'id' => $model->id ) ) );

?>

<div>

	<table class="transfer-details">
		<tbody>

		<tr>
			<th>ID перевода</th>
			<td><?php echo $model->id; ?></td>
		</tr>

		<tr>
			<th>Кто создал</th>
			<td><?php echo $model->session->user->getName(); ?></td>
		</tr>

		<tr>
			<th>Время и дата</th>
			<td><?php echo date( 'l, d F Y H:i', $model->timestamp ); ?></td>
		</tr>

		<tr>
			<th>Источник перевода</th>
			<td><?php echo $model->source_user->getName(); ?></td>
		</tr>

		<tr>
			<th>Получатель перевода</th>
			<td><?php echo $model->target_user->getName(); ?></td>
		</tr>

		<tr>
			<th>Сумма перевода</th>
			<td><?php echo $model->value; ?></td>
		</tr>

		<tr>
			<th>Комментарий</th>
			<td><?php echo XHtml::encode( $model->comment ); ?></td>
		</tr>

		</tbody>
	</table>


</div>