www/app/protected/controllers/ApiController.php
<?php

require_once Yii::getPathOfAlias('application.extensions.JsonRpc') . DIRECTORY_SEPARATOR . 'Server.php';
require_once Yii::getPathOfAlias('application.extensions.JsonRpc.Transport') . DIRECTORY_SEPARATOR . 'BasicServer.php';

class ApiController extends BaseController
{
    public $layout = false;

    public function accessRules()
    {
        return array(
            array('allow'),
        );
    }

    protected function beforeAction($action)
    {
        if (!parent::beforeAction($action)) {
            return false;
        }

        foreach (Yii::app()->log->routes as $route) {
            if ($route instanceof CWebLogRoute) {
                $route->enabled = false;
            }
        }

        return true;
    }

    public function actionIndex()
    {
        $server = new JsonRpc\Server(Yii::app()->api);

        if (Yii::app()->request->isPostRequest) {
            header('Content-Type: application/json');
            $server->receive();
            Yii::app()->end();
        }

        echo 'SMD here';
        Yii::app()->end();
    }

}

www/app/protected/controllers/PartiesController.php
<?php

class PartiesController extends BaseController
{
	public $pageTitle = 'Мои партии';

	public function init()
	{
		parent::init();

		$this->breadcrumbs = array(
			$this->pageTitle => array( 'index' ),
		);
	}

	public function accessRules()
	{
		return array_merge(
			array(),
			parent::accessRules()
		);
	}

	public function filters()
	{
		return array_merge(
			array(
				'postOnly + delete'
			),
			parent::filters()
		);
	}

	public function actionIndex()
	{
		$this->render( 'index', array(
			'parties' => Yii::app()->user->session->user->parties,
		) );
	}

	public function actionView( $uid = null )
	{
		$model = $this->loadParty( null, $uid );

		if ( !$model->isPartyMember() )
			$this->throwHttpException( 403, 'Чтобы просматривать страницу партии, нужно быть ее членом.' );

		$this->render( 'view', array(
			'model' => $model,
		) );
	}

	public function actionInvite( $uid )
	{
		$model = $this->loadParty( null, $uid );

		if ( !$model->isPartyMember() )
			$this->throwHttpException( 403, 'Чтобы просматривать страницу партии, нужно быть ее членом.' );

		$this->render( 'invite', array(
			'model' => $model,
		) );
	}

	public function actionJoin( $uid )
	{
		$model = $this->loadParty( null, $uid );

		if ( $model->isPartyMember() )
			$this->throwHttpException( 403, 'Вы уже вступили в эту партию.' );

		if ( Yii::app()->request->getIsPostRequest() )
		{
			if ( $model->joinUser() )
				$this->redirect( array( 'view', 'uid' => $model->uri_name ) );
		}

		$this->render( 'join', array(
			'model' => $model,
		) );
	}

	public function actionCreate()
	{
		$model = new Parties;

		$this->performAjaxValidation( $model );

		if ( isset( $_POST[ 'Parties' ] ) )
		{
			if ( $model->create( $_POST[ 'Parties' ] ) )
				$this->redirect( array( 'view', 'uid' => $model->uri_name ) );
		}

		$this->render( 'create', array(
			'model' => $model,
		) );
	}

	public function loadParty( $id = null, $uri_name = null )
	{
		/**/
		if ( isset( $id ) )
			return parent::loadModel( 'Parties', $id );
		else if ( isset( $uri_name ) )
			return parent::loadModel( 'Parties', $uri_name, 'uri_name' );

		$this->throwHttpException( 400, 'Отсутствует идентификатор партии.' );
	}

	protected function performAjaxValidation( $model )
	{
		if ( isset( $_POST[ 'ajax' ] ) && $_POST[ 'ajax' ] === 'parties-form' )
		{
			echo CActiveForm::validate( $model );
			Yii::app()->end();
		}
	}
}

www/app/protected/controllers/SiteController.php
<?php

class SiteController extends BaseController
{
	public $pageTitle = 'Welcome to Учёт Бабла';

	public function init()
	{
		parent::init();

		$this->breadcrumbs = array(
			$this->pageTitle => array( 'index' ),
		);
	}

	public function accessRules()
	{
		return array_merge(
			array(
				array( 'allow',
					/*'actions' => array('error')*/ ),
			),
			parent::accessRules()
		);
	}

	public function actions()
	{
		return array(
			'captcha' => array(
				'class' => 'CCaptchaAction',
				'backColor' => 0xFFFFFF,
			),
			'page' => array(
				'class' => 'CViewAction',
			),
		);
	}

	public function actionIndex()
	{
		$this->render( 'index' );
	}

	public function actionError()
	{
		if ( $error = Yii::app()->errorHandler->error )
		{
			if ( Yii::app()->request->isAjaxRequest )
				echo $error[ 'message' ]; // TODO
			else
				$this->render( 'error', $error );
		}
	}
	
	public function actionSendNotifications()
	{
		$users = Users::model()->findAllByAttributes( array(),
			'(`disabled` IS NULL OR `disabled` = 0 ) AND ( `locked_till` IS NULL OR `locked_till` < :current_timestamp ) AND `email` IS NOT NULL',
			array( ':current_timestamp' => time() ) );
		foreach ( $users as $user )
		{
			$transfers = new Transfers;
			$transfers->chiperkey = $user->salt;
			$creditors = $transfers->getCreditors();
			
			if ( empty( $creditors ) )
				continue;
			
			try
			{
				$email = Yii::app()->email;
				$email->to = $user->email;
				$email->view = 'notification';
				$email->viewVars = array(
					'user' => $user,
					'creditors' => $creditors,
				);
				$email->send();
			}
			catch (Exception $exception)
			{
				echo Yii::t( 'app', 'Something is going wrong when trying to send notification to {email}: {message}', array( '{email}' => $user->email, '{message}' => $exception->getMessage() ) );
			}
		}
	}

	public function actionContact()
	{
		$model = new ContactForm;
		if ( isset( $_POST[ 'ContactForm' ] ) )
		{
			$model->attributes = $_POST[ 'ContactForm' ];
			if ( $model->validate() )
			{
				$name = '=?UTF-8?B?'.base64_encode( $model->name ).'?=';
				$subject = '=?UTF-8?B?'.base64_encode( $model->subject ).'?=';
				$headers = "From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-type: text/plain; charset=UTF-8";

				mail( Yii::app()->params[ 'adminEmail' ], $subject, $model->body, $headers );
				Yii::app()->user->setFlash( 'contact', 'Thank you for contacting us. We will respond to you as soon as possible.' );
				$this->refresh();
			}
		}
		$this->render( 'contact', array( 'model' => $model ) );
	}
}

;

www/app/protected/controllers/TransfersController.php
<?php

class TransfersController extends BaseController
{
	public $pageTitle = 'Мои переводы';

	public function init()
	{
		parent::init();

		$this->breadcrumbs = array(
			$this->pageTitle => array( 'index' ),
		);
	}

	public function accessRules()
	{
		return array_merge(
			array(),
			parent::accessRules()
		);
	}

	public function filters()
	{
		return array_merge(
			array(
				'postOnly + delete'
			),
			parent::filters()
		);
	}

	public function actionIndex()
	{
		$pages = new CPagination( Transfers::model()->getHistoryCount() );
		$pages->pageSize = 10;

		$transfers = Transfers::model()->getHistory( $pages->limit, $pages->offset );

		$this->render( 'index', array(
			'transfers' => $transfers,
			'pages' => $pages,
		) );
	}

	public function actionTotal()
	{
		$this->render( 'total', array(
			'creditors' => Transfers::model()->getCreditors(),
			'debtors' => Transfers::model()->getDebtors(),
		) );
	}

	public function actionView( $id )
	{
		$model = Transfers::model()->getTransfer( $id );

		if ( $model === null )
			throwHttpNotFound( 'Запрошенный перевод не существует' );

		$this->render( 'view', array(
			'model' => $model,
		) );
	}

	public function actionCreate( $party_id = null, $source_user_id = null, $target_user_id = null )
	{
		$party_members = array( Yii::app()->user->session->user );
		$source_user = null;
		$target_user = null;

		if ( isset( $party_id ) )
		{
			$party = parent::loadModel( 'Parties', $party_id );
			$party_members = $party->users;
		}

		if ( isset( $source_user_id ) )
		{
			$source_user = parent::loadModel( 'Users', $source_user_id );
			$party_members[ ] = $source_user;
		}

		if ( isset( $target_user_id ) )
		{
			$target_user = parent::loadModel( 'Users', $target_user_id );
			$party_members[ ] = $target_user;
		}

		if ( empty( $party_members ) )
			$this->throwHttpException( 400, 'Неверный запрос. Не указаны обязательные параметры.' );

		$model = new Transfers;

		$this->performAjaxValidation( $model );

		if ( isset( $_POST[ 'Transfers' ] ) )
		{
			if ( $model->create( $_POST[ 'Transfers' ] ) )
			{
				Yii::app()->user->setFlash( 'system-highlight', 'Ваш перевод успешно создан.<br />'.XHtml::link( 'Создать еще один', array( 'create', 'party_id' => $party_id ) ) );
				$this->redirect( array( 'index' ) );
			}
		}

		$this->render( 'create', array(
			'model' => $model,
			'party_members' => $party_members,
			'source_user' => $source_user,
			'target_user' => $target_user,
		) );
	}

	public function actionCreateMultiple( $party_id )
	{
		$party = parent::loadModel( 'Parties', $party_id );

		$model = new Transfers;

		$this->performAjaxValidation( $model );

		if ( isset( $_POST[ 'Transfers' ] ) )
		{
			if ( $model->create( $_POST[ 'Transfers' ] ) )
			{
				Yii::app()->user->setFlash( 'system-highlight', 'Ваш перевод успешно создан.<br />'.XHtml::link( 'Создать еще один', array( 'create', 'party_id' => $party_id ) ) );
				$this->redirect( array( 'index' ) );
			}
		}

		$this->render( 'create_multiple', array(
			'model' => $model,
			'party_members' => $party->users,
		) );
	}

	protected function performAjaxValidation( $model )
	{
		if ( isset( $_POST[ 'ajax' ] ) && $_POST[ 'ajax' ] === 'transfers-form' )
		{
			echo CActiveForm::validate( $model );
			Yii::app()->end();
		}
	}
}

;

www/app/protected/controllers/UsersController.php
<?php

class UsersController extends BaseController
{
	public $pageTitle = 'Пользователи';

	public function init()
	{
		parent::init();

		$this->breadcrumbs = array(
			$this->pageTitle => array( 'index' ),
		);
	}

	public function accessRules()
	{
		return array_merge(
			array(
				array( 'allow',
					'actions' => array( 'index', 'login', 'vkauth' ) ),
			),
			parent::accessRules()
		);
	}

	public function actionIndex()
	{
		$this->redirect( '/users/login' );
	}

	public function actionLogin()
	{
		if ( !Yii::app()->user->isGuest )
			$this->redirect( Yii::app()->homeUrl );

		$model = new LoginForm;

		if ( isset( $_POST[ 'ajax' ] ) && $_POST[ 'ajax' ] === 'login-form' )
		{
			echo CActiveForm::validate( $model );
			Yii::app()->end();
		}

		if ( isset( $_POST[ 'LoginForm' ] ) )
		{
			$model->attributes = $_POST[ 'LoginForm' ];

			if ( $model->validate() && $model->login() )
				$this->redirect( Yii::app()->request->urlReferrer ? Yii::app()->request->urlReferrer : Yii::app()->returnUrl );
		}

		$this->render( 'login', array( 'model' => $model ) );
	}

	public function actionVkauth()
	{
		if ( !Yii::app()->user->isGuest )
			$this->redirect( Yii::app()->homeUrl );

		$user_identity = new VkAppIdentity();
		$user_identity->authenticate();

		if ( $user_identity->errorCode === BaseIdentity::ERROR_NONE &&
			Yii::app()->user->login( $user_identity )
		)
		{
			$this->redirect( Yii::app()->request->urlReferrer ? Yii::app()->request->urlReferrer : Yii::app()->returnUrl );
		}

		$this->redirect( '/users/login' );
	}

	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect( Yii::app()->request->urlReferrer ? Yii::app()->request->urlReferrer : Yii::app()->homeUrl );
	}

	public function actionEmail()
	{
		$model = new EmailForm;

		if ( isset( $_POST[ 'ajax' ] ) && $_POST[ 'ajax' ] === 'email-form' )
		{
			echo CActiveForm::validate( $model );
			Yii::app()->end();
		}

		if ( isset( $_POST[ 'EmailForm' ] ) )
		{
			$model->attributes = $_POST[ 'EmailForm' ];

			if ( $model->validate() && $model->setEmail() )
				$this->redirect( Yii::app()->homeUrl );
		}

		$this->render( 'email', array( 'model' => $model ) );
	}

	public function actionBankAccount()
	{
		$model = BankAccounts::model()->findByAttributes( array(
			'user_id' => Yii::app()->user->id
		) );

		if ( $model === null )
			$model = new BankAccounts;

		if ( isset( $_POST[ 'ajax' ] ) && $_POST[ 'ajax' ] === 'bank-account-form' )
		{
			echo CActiveForm::validate( $model );
			Yii::app()->end();
		}

		if ( isset( $_POST[ 'BankAccounts' ] ) )
		{
			$model->attributes = $_POST[ 'BankAccounts' ];
			$model->user_id = Yii::app()->user->id;

			if ( $model->save() )
				$this->redirect( Yii::app()->homeUrl );
		}

		$this->render( 'bankAccount', array( 'model' => $model ) );
	}

}

www/app/protected/views/controllers/parties/_form.php
<?php $this->widget( 'XActiveForm', array(
	'id' => 'parties-form',
	'enableAjaxValidation' => true,
	'clientOptions' => array(
		'validateOnSubmit' => true,
		'validateOnChange' => false,
	),
	'model' => $model,
	'fields' => array
	(
		'name',
		'email' => array( 'type' => 'email' ),
	),
) ); ?>

www/app/protected/views/controllers/parties/_navigation_links.php
<ul>
	<li><?php echo XHtml::link( 'Новый перевод', array( '/transfers/create', 'party_id' => $model->id ), array( 'class' => 'big-link' ) ); ?></li>
</ul>
<ul>
	<li><?php echo XHtml::link( 'Перевод многим', array( '/transfers/CreateMultiple', 'party_id' => $model->id ), array( 'class' => 'big-link' ) ); ?></li>
</ul>

www/app/protected/views/controllers/parties/create.php
<?php

$this->pageTitle = 'Основать партию';
$this->breadcrumbs = array_merge( $this->breadcrumbs,
	array( $this->pageTitle => array( 'create' ) ) );

?>

<?php echo $this->renderPartial( '_form', array( 'model' => $model ) ); ?>

www/app/protected/views/controllers/parties/index.php
<?php

echo XHtml::link( 'Основать партию', array( 'create' ), array( 'class' => 'big-link float-right' ) );

?>

<div class="mainbar">

	<?php
	foreach ( $parties as $party )
		echo XHtml::tag( 'h3', array(),
			XHtml::link( $party->name, array( $this->id.'/view/', 'uid' => $party->uri_name ), array( 'class' => 'big-link' ) ).'<br />' );
	?>

</div>

<div class="sidebar">
</div>

www/app/protected/views/controllers/parties/invite.php
<?php

$this->pageTitle = $model->name;
$this->breadcrumbs = array_merge( $this->breadcrumbs,
	array( $this->pageTitle => array( 'view', 'id' => $model->id ) ) );

echo XHtml::link( 'Основать партию', array( 'create' ), array( 'class' => 'big-link float-right' ) );

?>

<div class="mainbar">

	<p>Чтобы пригласить в партию своего камрада, предложите ему пройти по ссылке:<br />

	<h3 class="tab-started"><?php echo XHtml::link( Yii::app()->createAbsoluteUrl( $this->id.'/join', array( 'uid' => $model->uri_name ) ),
			Yii::app()->createAbsoluteUrl( $this->id.'/join', array( 'uid' => $model->uri_name ) ), array( 'class' => 'big-link' ) ) ?></h3></p>

</div>

<div class="sidebar navigation-links">
	<?php $this->renderPartial( '_navigation_links', array( 'model' => $model ) ); ?>
</div>

www/app/protected/views/controllers/parties/join.php
<?php

$this->pageTitle = $model->name;
$this->breadcrumbs = array_merge( $this->breadcrumbs,
	array( $this->pageTitle => array( 'view', 'id' => $model->id ) ) );

echo XHtml::link( 'Основать партию', array( 'create' ), array( 'class' => 'big-link float-right' ) );

?>

<div class="mainbar">

	<p>Чтобы вступить в партию «<?php echo $model->name; ?>» нажмите кнопку «Вступить».</p>

	<?php $this->widget( 'XActiveForm', array(
		'fields' => array
		(),
		'buttons' => array
		(
			'submit' => XHtml::submitButton( 'Вступить' ),
		)
	) ); ?>

</div>

<div class="sidebar">
</div>

www/app/protected/views/controllers/parties/view.php
<?php

$this->pageTitle = $model->name;
$this->breadcrumbs = array_merge( $this->breadcrumbs,
	array( $this->pageTitle => array( 'view', 'uid' => $model->uri_name ) ) );

echo XHtml::link( 'Пригласить в партию', array( 'invite', 'uid' => $model->uri_name ), array( 'class' => 'big-link float-right' ) );

?>

<div class="mainbar">

	<?php
	if ( empty( $model->users ) )
		echo '<p>В партии никто не состоит :(</p>';
	else
	{
		?>

		<p>Список членов партии:</p>
		<ul class="no-list-style-type">
			<?php
			if ( empty( $model->users ) )
				echo 'В ней никого нет :(';

			foreach ( $model->users as $user )
				echo XHtml::tag( 'li', array(), '<h3>'.$user->getName().'</h3>' );
			?>
		</ul>

	<?php } ?>

</div>

<div class="sidebar navigation-links">
	<?php $this->renderPartial( '_navigation_links', array( 'model' => $model ) ); ?>
</div>