www/app/protected/controllers/ApiController.php
<?php

require_once Yii::getPathOfAlias('application.extensions.JsonRpc') . DIRECTORY_SEPARATOR . 'Server.php';
require_once Yii::getPathOfAlias('application.extensions.JsonRpc.Transport') . DIRECTORY_SEPARATOR . 'BasicServer.php';

class ApiController extends BaseController
{
    public $layout = false;

    public function accessRules()
    {
        return array(
            array('allow'),
        );
    }

    protected function beforeAction($action)
    {
        if (!parent::beforeAction($action)) {
            return false;
        }

        foreach (Yii::app()->log->routes as $route) {
            if ($route instanceof CWebLogRoute) {
                $route->enabled = false;
            }
        }

        return true;
    }

    public function actionIndex()
    {
        $server = new JsonRpc\Server(Yii::app()->api);

        if (Yii::app()->request->isPostRequest) {
            header('Content-Type: application/json');
            $server->receive();
            Yii::app()->end();
        }

        echo 'SMD here';
        Yii::app()->end();
    }

}

www/app/protected/controllers/PartiesController.php
<?php

class PartiesController extends BaseController
{
	public $pageTitle = 'Мои партии';

	public function init()
	{
		parent::init();

		$this->breadcrumbs = array(
			$this->pageTitle => array( 'index' ),
		);
	}

	public function accessRules()
	{
		return array_merge(
			array(),
			parent::accessRules()
		);
	}

	public function filters()
	{
		return array_merge(
			array(
				'postOnly + delete'
			),
			parent::filters()
		);
	}

	public function actionIndex()
	{
		$this->render( 'index', array(
			'parties' => Yii::app()->user->session->user->parties,
		) );
	}

	public function actionView( $uid = null )
	{
		$model = $this->loadParty( null, $uid );

		if ( !$model->isPartyMember() )
			$this->throwHttpException( 403, 'Чтобы просматривать страницу партии, нужно быть ее членом.' );

		$this->render( 'view', array(
			'model' => $model,
		) );
	}

	public function actionInvite( $uid )
	{
		$model = $this->loadParty( null, $uid );

		if ( !$model->isPartyMember() )
			$this->throwHttpException( 403, 'Чтобы просматривать страницу партии, нужно быть ее членом.' );

		$this->render( 'invite', array(
			'model' => $model,
		) );
	}

	public function actionJoin( $uid )
	{
		$model = $this->loadParty( null, $uid );

		if ( $model->isPartyMember() )
			$this->throwHttpException( 403, 'Вы уже вступили в эту партию.' );

		if ( Yii::app()->request->getIsPostRequest() )
		{
			if ( $model->joinUser() )
				$this->redirect( array( 'view', 'uid' => $model->uri_name ) );
		}

		$this->render( 'join', array(
			'model' => $model,
		) );
	}

	public function actionCreate()
	{
		$model = new Parties;

		$this->performAjaxValidation( $model );

		if ( isset( $_POST[ 'Parties' ] ) )
		{
			if ( $model->create( $_POST[ 'Parties' ] ) )
				$this->redirect( array( 'view', 'uid' => $model->uri_name ) );
		}

		$this->render( 'create', array(
			'model' => $model,
		) );
	}

	public function loadParty( $id = null, $uri_name = null )
	{
		/**/
		if ( isset( $id ) )
			return parent::loadModel( 'Parties', $id );
		else if ( isset( $uri_name ) )
			return parent::loadModel( 'Parties', $uri_name, 'uri_name' );

		$this->throwHttpException( 400, 'Отсутствует идентификатор партии.' );
	}

	protected function performAjaxValidation( $model )
	{
		if ( isset( $_POST[ 'ajax' ] ) && $_POST[ 'ajax' ] === 'parties-form' )
		{
			echo CActiveForm::validate( $model );
			Yii::app()->end();
		}
	}
}

www/app/protected/controllers/SiteController.php
<?php

class SiteController extends BaseController
{
	public $pageTitle = 'Welcome to Учёт Бабла';

	public function init()
	{
		parent::init();

		$this->breadcrumbs = array(
			$this->pageTitle => array( 'index' ),
		);
	}

	public function accessRules()
	{
		return array_merge(
			array(
				array( 'allow',
					/*'actions' => array('error')*/ ),
			),
			parent::accessRules()
		);
	}

	public function actions()
	{
		return array(
			'captcha' => array(
				'class' => 'CCaptchaAction',
				'backColor' => 0xFFFFFF,
			),
			'page' => array(
				'class' => 'CViewAction',
			),
		);
	}

	public function actionIndex()
	{
		$this->render( 'index' );
	}

	public function actionError()
	{
		if ( $error = Yii::app()->errorHandler->error )
		{
			if ( Yii::app()->request->isAjaxRequest )
				echo $error[ 'message' ]; // TODO
			else
				$this->render( 'error', $error );
		}
	}
	
	public function actionSendNotifications()
	{
		$users = Users::model()->findAllByAttributes( array(),
			'(`disabled` IS NULL OR `disabled` = 0 ) AND ( `locked_till` IS NULL OR `locked_till` < :current_timestamp ) AND `email` IS NOT NULL',
			array( ':current_timestamp' => time() ) );
		foreach ( $users as $user )
		{
			$transfers = new Transfers;
			$transfers->chiperkey = $user->salt;
			$creditors = $transfers->getCreditors();
			
			if ( empty( $creditors ) )
				continue;
			
			try
			{
				$email = Yii::app()->email;
				$email->to = $user->email;
				$email->view = 'notification';
				$email->viewVars = array(
					'user' => $user,
					'creditors' => $creditors,
				);
				$email->send();
			}
			catch (Exception $exception)
			{
				echo Yii::t( 'app', 'Something is going wrong when trying to send notification to {email}: {message}', array( '{email}' => $user->email, '{message}' => $exception->getMessage() ) );
			}
		}
	}

	public function actionContact()
	{
		$model = new ContactForm;
		if ( isset( $_POST[ 'ContactForm' ] ) )
		{
			$model->attributes = $_POST[ 'ContactForm' ];
			if ( $model->validate() )
			{
				$name = '=?UTF-8?B?'.base64_encode( $model->name ).'?=';
				$subject = '=?UTF-8?B?'.base64_encode( $model->subject ).'?=';
				$headers = "From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-type: text/plain; charset=UTF-8";

				mail( Yii::app()->params[ 'adminEmail' ], $subject, $model->body, $headers );
				Yii::app()->user->setFlash( 'contact', 'Thank you for contacting us. We will respond to you as soon as possible.' );
				$this->refresh();
			}
		}
		$this->render( 'contact', array( 'model' => $model ) );
	}
}

;

www/app/protected/controllers/TransfersController.php
<?php

class TransfersController extends BaseController
{
	public $pageTitle = 'Мои переводы';

	public function init()
	{
		parent::init();

		$this->breadcrumbs = array(
			$this->pageTitle => array( 'index' ),
		);
	}

	public function accessRules()
	{
		return array_merge(
			array(),
			parent::accessRules()
		);
	}

	public function filters()
	{
		return array_merge(
			array(
				'postOnly + delete'
			),
			parent::filters()
		);
	}

	public function actionIndex()
	{
		$pages = new CPagination( Transfers::model()->getHistoryCount() );
		$pages->pageSize = 10;

		$transfers = Transfers::model()->getHistory( $pages->limit, $pages->offset );

		$this->render( 'index', array(
			'transfers' => $transfers,
			'pages' => $pages,
		) );
	}

	public function actionTotal()
	{
		$this->render( 'total', array(
			'creditors' => Transfers::model()->getCreditors(),
			'debtors' => Transfers::model()->getDebtors(),
		) );
	}

	public function actionView( $id )
	{
		$model = Transfers::model()->getTransfer( $id );

		if ( $model === null )
			throwHttpNotFound( 'Запрошенный перевод не существует' );

		$this->render( 'view', array(
			'model' => $model,
		) );
	}

	public function actionCreate( $party_id = null, $source_user_id = null, $target_user_id = null )
	{
		$party_members = array( Yii::app()->user->session->user );
		$source_user = null;
		$target_user = null;

		if ( isset( $party_id ) )
		{
			$party = parent::loadModel( 'Parties', $party_id );
			$party_members = $party->users;
		}

		if ( isset( $source_user_id ) )
		{
			$source_user = parent::loadModel( 'Users', $source_user_id );
			$party_members[ ] = $source_user;
		}

		if ( isset( $target_user_id ) )
		{
			$target_user = parent::loadModel( 'Users', $target_user_id );
			$party_members[ ] = $target_user;
		}

		if ( empty( $party_members ) )
			$this->throwHttpException( 400, 'Неверный запрос. Не указаны обязательные параметры.' );

		$model = new Transfers;

		$this->performAjaxValidation( $model );

		if ( isset( $_POST[ 'Transfers' ] ) )
		{
			if ( $model->create( $_POST[ 'Transfers' ] ) )
			{
				Yii::app()->user->setFlash( 'system-highlight', 'Ваш перевод успешно создан.<br />'.XHtml::link( 'Создать еще один', array( 'create', 'party_id' => $party_id ) ) );
				$this->redirect( array( 'index' ) );
			}
		}

		$this->render( 'create', array(
			'model' => $model,
			'party_members' => $party_members,
			'source_user' => $source_user,
			'target_user' => $target_user,
		) );
	}

	public function actionCreateMultiple( $party_id )
	{
		$party = parent::loadModel( 'Parties', $party_id );

		$model = new Transfers;

		$this->performAjaxValidation( $model );

		if ( isset( $_POST[ 'Transfers' ] ) )
		{
			if ( $model->create( $_POST[ 'Transfers' ] ) )
			{
				Yii::app()->user->setFlash( 'system-highlight', 'Ваш перевод успешно создан.<br />'.XHtml::link( 'Создать еще один', array( 'create', 'party_id' => $party_id ) ) );
				$this->redirect( array( 'index' ) );
			}
		}

		$this->render( 'create_multiple', array(
			'model' => $model,
			'party_members' => $party->users,
		) );
	}

	protected function performAjaxValidation( $model )
	{
		if ( isset( $_POST[ 'ajax' ] ) && $_POST[ 'ajax' ] === 'transfers-form' )
		{
			echo CActiveForm::validate( $model );
			Yii::app()->end();
		}
	}
}

;

www/app/protected/controllers/UsersController.php
<?php

class UsersController extends BaseController
{
	public $pageTitle = 'Пользователи';

	public function init()
	{
		parent::init();

		$this->breadcrumbs = array(
			$this->pageTitle => array( 'index' ),
		);
	}

	public function accessRules()
	{
		return array_merge(
			array(
				array( 'allow',
					'actions' => array( 'index', 'login', 'vkauth' ) ),
			),
			parent::accessRules()
		);
	}

	public function actionIndex()
	{
		$this->redirect( '/users/login' );
	}

	public function actionLogin()
	{
		if ( !Yii::app()->user->isGuest )
			$this->redirect( Yii::app()->homeUrl );

		$model = new LoginForm;

		if ( isset( $_POST[ 'ajax' ] ) && $_POST[ 'ajax' ] === 'login-form' )
		{
			echo CActiveForm::validate( $model );
			Yii::app()->end();
		}

		if ( isset( $_POST[ 'LoginForm' ] ) )
		{
			$model->attributes = $_POST[ 'LoginForm' ];

			if ( $model->validate() && $model->login() )
				$this->redirect( Yii::app()->request->urlReferrer ? Yii::app()->request->urlReferrer : Yii::app()->returnUrl );
		}

		$this->render( 'login', array( 'model' => $model ) );
	}

	public function actionVkauth()
	{
		if ( !Yii::app()->user->isGuest )
			$this->redirect( Yii::app()->homeUrl );

		$user_identity = new VkAppIdentity();
		$user_identity->authenticate();

		if ( $user_identity->errorCode === BaseIdentity::ERROR_NONE &&
			Yii::app()->user->login( $user_identity )
		)
		{
			$this->redirect( Yii::app()->request->urlReferrer ? Yii::app()->request->urlReferrer : Yii::app()->returnUrl );
		}

		$this->redirect( '/users/login' );
	}

	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect( Yii::app()->request->urlReferrer ? Yii::app()->request->urlReferrer : Yii::app()->homeUrl );
	}

	public function actionEmail()
	{
		$model = new EmailForm;

		if ( isset( $_POST[ 'ajax' ] ) && $_POST[ 'ajax' ] === 'email-form' )
		{
			echo CActiveForm::validate( $model );
			Yii::app()->end();
		}

		if ( isset( $_POST[ 'EmailForm' ] ) )
		{
			$model->attributes = $_POST[ 'EmailForm' ];

			if ( $model->validate() && $model->setEmail() )
				$this->redirect( Yii::app()->homeUrl );
		}

		$this->render( 'email', array( 'model' => $model ) );
	}

	public function actionBankAccount()
	{
		$model = BankAccounts::model()->findByAttributes( array(
			'user_id' => Yii::app()->user->id
		) );

		if ( $model === null )
			$model = new BankAccounts;

		if ( isset( $_POST[ 'ajax' ] ) && $_POST[ 'ajax' ] === 'bank-account-form' )
		{
			echo CActiveForm::validate( $model );
			Yii::app()->end();
		}

		if ( isset( $_POST[ 'BankAccounts' ] ) )
		{
			$model->attributes = $_POST[ 'BankAccounts' ];
			$model->user_id = Yii::app()->user->id;

			if ( $model->save() )
				$this->redirect( Yii::app()->homeUrl );
		}

		$this->render( 'bankAccount', array( 'model' => $model ) );
	}

}

www/app/protected/views/controllers/site/contact.php
<?php
/* @var $this SiteController */
/* @var $model ContactForm */
/* @var $form CActiveForm */

$this->pageTitle = Yii::app()->name.' - Contact Us';
$this->breadcrumbs = array(
	'Contact',
);
?>

	<h1>Contact Us</h1>

<?php if ( Yii::app()->user->hasFlash( 'contact' ) ): ?>

	<div class="flash-success">
		<?php echo Yii::app()->user->getFlash( 'contact' ); ?>
	</div>

<?php else: ?>

	<p>
		If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
	</p>

	<div class="form">

		<?php $form = $this->beginWidget( 'CActiveForm', array(
			'id' => 'contact-form',
			'enableClientValidation' => true,
			'clientOptions' => array(
				'validateOnSubmit' => true,
			),
		) ); ?>

		<p class="note">Fields with <span class="required">*</span> are required.</p>

		<?php echo $form->errorSummary( $model ); ?>

		<div class="row">
			<?php echo $form->labelEx( $model, 'name' ); ?>
			<?php echo $form->textField( $model, 'name' ); ?>
			<?php echo $form->error( $model, 'name' ); ?>
		</div>

		<div class="row">
			<?php echo $form->labelEx( $model, 'email' ); ?>
			<?php echo $form->textField( $model, 'email' ); ?>
			<?php echo $form->error( $model, 'email' ); ?>
		</div>

		<div class="row">
			<?php echo $form->labelEx( $model, 'subject' ); ?>
			<?php echo $form->textField( $model, 'subject', array( 'size' => 60, 'maxlength' => 128 ) ); ?>
			<?php echo $form->error( $model, 'subject' ); ?>
		</div>

		<div class="row">
			<?php echo $form->labelEx( $model, 'body' ); ?>
			<?php echo $form->textArea( $model, 'body', array( 'rows' => 6, 'cols' => 50 ) ); ?>
			<?php echo $form->error( $model, 'body' ); ?>
		</div>

		<?php if ( CCaptcha::checkRequirements() ): ?>
			<div class="row">
				<?php echo $form->labelEx( $model, 'verifyCode' ); ?>
				<div>
					<?php $this->widget( 'CCaptcha' ); ?>
					<?php echo $form->textField( $model, 'verifyCode' ); ?>
				</div>
				<div class="hint">Please enter the letters as they are shown in the image above.
					<br />Letters are not case-sensitive.
				</div>
				<?php echo $form->error( $model, 'verifyCode' ); ?>
			</div>
		<?php endif; ?>

		<div class="row buttons">
			<?php echo CHtml::submitButton( 'Submit' ); ?>
		</div>

		<?php $this->endWidget(); ?>

	</div><!-- form -->

<?php endif; ?>

www/app/protected/views/controllers/site/error.php
<?php
/* @var $this SiteController */
/* @var $error array */

$this->pageTitle = '';
$this->breadcrumbs = false;
?>

<div class="error-message">
	<?php echo nl2br( XHtml::encode( $message ) ); ?>
</div>

www/app/protected/views/controllers/site/index.php
<p>Здесь вы можете:</p>
<ul>
	<li>создавать Партии;</li>
	<li>вступать в Партии;</li>
	<li>уплачивать членские взносы в Партии;</li>
	<li>смотреть на тех, кто еще не уплатил.</li>
</ul>

<p>Для оперативного информирования вас о происходящем неплохо
	бы <?php echo XHtml::link( 'указать свою почту', array( '/users/email' ) ); ?>.</p>

<p>Для удобства получения взносов от других товарищей <?php echo XHtml::link( 'укажите свои реквизиты', array( '/users/bankAccount' ) ); ?>.</p>